// Generated by scripts/sync-dactyl.py. Edit PodlodkaDive/ sources, then regenerate.
import Combine
import Foundation
import QuartzCore
import SwiftUI
import UIKit

// MARK: - GameEngine.swift

enum RunState: Equatable { case ready, playing, paused, gameOver, completed }
enum FailureReason { case hull, energy }
enum PickupKind: String { case battery, shield, sample, blackBox }
enum MinePhase { case idle, armed, exploding, spent }

struct OceanPickup: Identifiable {
    let id: Int
    let kind: PickupKind
    let position: CGPoint
    var collected = false
}

struct OceanMine: Identifiable {
    let id: Int
    let position: CGPoint
    var phase: MinePhase = .idle
    var timer: TimeInterval = 0
    static let triggerRadius: CGFloat = 120
    static let blastRadius: CGFloat = 96
    static let fuse: TimeInterval = 1.25
}

struct OceanCurrent: Identifiable {
    let id: Int
    let bounds: CGRect
    let velocity: CGVector
}

struct RockContact {
    let normal: CGVector
    let penetration: CGFloat
}

struct OceanRock: Identifiable {
    let id: Int
    let vertices: [CGPoint]

    var bounds: CGRect {
        guard let first = vertices.first else { return .zero }
        let xs = vertices.map(\.x), ys = vertices.map(\.y)
        return CGRect(x: xs.min() ?? first.x, y: ys.min() ?? first.y,
                      width: (xs.max() ?? first.x) - (xs.min() ?? first.x),
                      height: (ys.max() ?? first.y) - (ys.min() ?? first.y))
    }

    /// Circle against the exact polygon also handles corners and starting inside.
    func contact(at point: CGPoint, radius: CGFloat) -> RockContact? {
        guard vertices.count >= 3, bounds.insetBy(dx: -radius, dy: -radius).contains(point) else { return nil }
        var inside = false
        var closest = vertices[0]
        var nearestSquared = CGFloat.infinity
        var edgeNormal = CGVector(dx: 1, dy: 0)
        var area: CGFloat = 0
        for index in vertices.indices {
            let a = vertices[index], b = vertices[(index + 1) % vertices.count]
            area += a.x * b.y - b.x * a.y
            if (a.y > point.y) != (b.y > point.y),
               point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x { inside.toggle() }
            let dx = b.x - a.x, dy = b.y - a.y
            let lengthSquared = dx * dx + dy * dy
            let t = lengthSquared > 0 ? min(1, max(0, ((point.x - a.x) * dx + (point.y - a.y) * dy) / lengthSquared)) : 0
            let candidate = CGPoint(x: a.x + dx * t, y: a.y + dy * t)
            let d = pow(point.x - candidate.x, 2) + pow(point.y - candidate.y, 2)
            if d < nearestSquared {
                closest = candidate
                nearestSquared = d
                let length = max(0.001, sqrt(lengthSquared))
                edgeNormal = CGVector(dx: dy / length, dy: -dx / length)
            }
        }
        let distance = sqrt(nearestSquared)
        guard inside || distance < radius else { return nil }
        let sign: CGFloat = inside ? -1 : 1
        let normal = distance > 0.001
            ? CGVector(dx: (point.x - closest.x) / distance * sign, dy: (point.y - closest.y) / distance * sign)
            : CGVector(dx: edgeNormal.dx * (area >= 0 ? 1 : -1), dy: edgeNormal.dy * (area >= 0 ? 1 : -1))
        return RockContact(normal: normal, penetration: inside ? radius + distance : radius - distance)
    }
}

struct OceanLevel {
    let size: CGSize
    let spawn: CGPoint
    let base: CGPoint
    let wreck: CGPoint
    var rocks: [OceanRock] = []
    var pickups: [OceanPickup] = []
    var mines: [OceanMine] = []
    var currents: [OceanCurrent] = []

    static var expedition: OceanLevel {
        func rock(_ id: Int, _ points: [(CGFloat, CGFloat)]) -> OceanRock {
            OceanRock(id: id, vertices: points.map { CGPoint(x: $0.0, y: $0.1) })
        }
        func pickup(_ id: Int, _ kind: PickupKind, _ x: CGFloat, _ y: CGFloat) -> OceanPickup {
            OceanPickup(id: id, kind: kind, position: CGPoint(x: x, y: y))
        }
        return OceanLevel(
            size: CGSize(width: 1560, height: 2600), spawn: CGPoint(x: 245, y: 290),
            base: CGPoint(x: 190, y: 230), wreck: CGPoint(x: 1370, y: 2330),
            rocks: [
                rock(0, [(345, 480), (510, 445), (630, 535), (665, 730), (560, 920), (345, 875), (290, 690)]),
                rock(1, [(1080, 425), (1430, 480), (1480, 700), (1390, 960), (1060, 905), (985, 650)]),
                rock(2, [(700, 1140), (965, 1120), (1070, 1310), (1000, 1550), (770, 1620), (595, 1450), (610, 1260)]),
                rock(3, [(110, 1460), (245, 1410), (350, 1570), (320, 1880), (170, 1990), (75, 1810)]),
                rock(4, [(1010, 1860), (1160, 1820), (1260, 1970), (1200, 2130), (995, 2160), (895, 2030)]),
                rock(5, [(580, 2230), (720, 2200), (805, 2350), (725, 2520), (515, 2530), (470, 2380)])
            ],
            pickups: [
                pickup(0, .blackBox, 1370, 2330),
                pickup(1, .battery, 185, 1070), pickup(2, .battery, 440, 1780),
                pickup(3, .battery, 1480, 2470), pickup(4, .battery, 1450, 1240),
                pickup(5, .shield, 790, 470), pickup(6, .shield, 860, 2260),
                pickup(7, .sample, 390, 320), pickup(8, .sample, 740, 830),
                pickup(9, .sample, 1220, 1080), pickup(10, .sample, 465, 1370),
                pickup(11, .sample, 820, 1770), pickup(12, .sample, 1350, 1660),
                pickup(13, .sample, 190, 2250), pickup(14, .sample, 900, 2450)
            ],
            mines: [
                OceanMine(id: 0, position: CGPoint(x: 820, y: 700)),
                OceanMine(id: 1, position: CGPoint(x: 875, y: 1030)),
                OceanMine(id: 2, position: CGPoint(x: 1190, y: 1390)),
                OceanMine(id: 3, position: CGPoint(x: 1370, y: 1950)),
                OceanMine(id: 4, position: CGPoint(x: 440, y: 2190)),
                OceanMine(id: 5, position: CGPoint(x: 1060, y: 2420))
            ],
            currents: [
                OceanCurrent(id: 0, bounds: CGRect(x: 725, y: 540, width: 205, height: 490), velocity: CGVector(dx: 0, dy: 48)),
                OceanCurrent(id: 1, bounds: CGRect(x: 520, y: 1645, width: 780, height: 155), velocity: CGVector(dx: 58, dy: 0)),
                OceanCurrent(id: 2, bounds: CGRect(x: 1290, y: 1460, width: 230, height: 750), velocity: CGVector(dx: 0, dy: -38))
            ])
    }
}

@MainActor
final class GameEngine: NSObject, ObservableObject {
    @Published private(set) var state: RunState = .ready
    @Published private(set) var elapsed: TimeInterval = 0
    @Published private(set) var bestScore: Int
    @Published private(set) var pickupCount = 0
    @Published private(set) var damageCount = 0

    let level: OceanLevel
    private(set) var viewport = CGSize(width: 390, height: 844)
    private(set) var position: CGPoint
    private(set) var velocity = CGVector.zero
    private(set) var steering = CGVector.zero
    private(set) var camera = CGPoint.zero
    private(set) var facing: CGFloat = 1
    private(set) var energy: CGFloat = 100
    private(set) var hull = 3
    private(set) var hasShield = false
    private(set) var hasBlackBox = false
    private(set) var samples = 0
    private(set) var score = 0
    private(set) var bestAtStart = 0
    private(set) var runElapsed: TimeInterval = 0
    private(set) var distance: CGFloat = 0
    private(set) var boostRemaining: TimeInterval = 0
    private(set) var boostCooldown: TimeInterval = 0
    private(set) var sonarRemaining: TimeInterval = 0
    private(set) var sonarCooldown: TimeInterval = 0
    private(set) var invulnerability: TimeInterval = 0
    private(set) var pickups: [OceanPickup]
    private(set) var mines: [OceanMine]
    private(set) var revealedPickups: Set<Int> = []
    private(set) var trail: [CGPoint] = []
    private(set) var notice = ""
    private(set) var noticeRemaining: TimeInterval = 0
    private(set) var failureReason: FailureReason = .hull

    private var boostDirection = CGVector(dx: 1, dy: 0)
    private var displayLink: CADisplayLink?
    private var previousTimestamp: CFTimeInterval?
    private var accumulator: TimeInterval = 0
    private let defaults: UserDefaults
    private static let bestKey = "podlodkaDive.expedition.bestSalvage"
    static let hullRadius: CGFloat = 20
    static let cruiseSpeed: CGFloat = 96
    static let boostCost: CGFloat = 7
    private static let fixedStep: TimeInterval = 1.0 / 120.0

    init(defaults: UserDefaults = .standard, level: OceanLevel = .expedition) {
        self.defaults = defaults
        self.level = level
        position = level.spawn
        pickups = level.pickups
        mines = level.mines
        bestScore = defaults.integer(forKey: Self.bestKey)
        super.init()
        updateCamera(dt: 1, snap: true)
    }

    var speed: CGFloat { hypot(velocity.dx, velocity.dy) }
    var inputStrength: CGFloat { hypot(steering.dx, steering.dy) }
    var isThrustActive: Bool { state == .playing && (inputStrength > 0 || boostRemaining > 0) }
    var cargoValue: Int { samples * 75 + (hasBlackBox ? 600 : 0) }
    var depth: Int { Int(max(0, position.y - 100) * 0.16) }
    var target: CGPoint { hasBlackBox ? level.base : level.wreck }
    var targetDistance: Int { Int(hypot(target.x - position.x, target.y - position.y) * 0.16) }
    var isNewRecord: Bool { state == .completed && score > bestAtStart }
    var canBoost: Bool { state == .playing && boostCooldown <= 0 && energy >= Self.boostCost }
    var canSonar: Bool { state == .playing && sonarCooldown <= 0 }
    var submarineRotationRadians: Double { Double(atan2(velocity.dy, max(55, abs(velocity.dx)))) * 0.55 }

    func resize(to size: CGSize) {
        guard size.width.isFinite, size.height.isFinite, size.width > 0, size.height > 0 else { return }
        let next = CGSize(width: 390, height: size.height * 390 / size.width)
        guard next != viewport else { return }
        viewport = next
        pause()
        updateCamera(dt: 1, snap: true)
        objectWillChange.send()
    }

    func startGame() {
        position = level.spawn
        velocity = .zero
        steering = .zero
        facing = 1
        energy = 100
        hull = 3
        hasShield = false
        hasBlackBox = false
        samples = 0
        score = 0
        bestAtStart = bestScore
        runElapsed = 0
        distance = 0
        boostRemaining = 0
        boostCooldown = 0
        sonarRemaining = 0
        sonarCooldown = 0
        invulnerability = 0
        pickups = level.pickups
        mines = level.mines
        revealedPickups = []
        trail = [position]
        accumulator = 0
        previousTimestamp = nil
        announce("Найди чёрный ящик. Сохрани заряд на возвращение.", duration: 7)
        updateCamera(dt: 1, snap: true)
        state = .playing
    }

    func returnToMenu() {
        steering = .zero
        velocity = .zero
        state = .ready
        previousTimestamp = nil
        accumulator = 0
    }

    func setSteering(_ vector: CGVector) {
        guard state == .playing, vector.dx.isFinite, vector.dy.isFinite else { return }
        let length = hypot(vector.dx, vector.dy)
        if length < 0.08 { steering = .zero }
        else { steering = CGVector(dx: vector.dx / max(1, length), dy: vector.dy / max(1, length)) }
        objectWillChange.send()
    }

    func activateBoost() {
        guard canBoost else { return }
        let length = inputStrength
        boostDirection = length > 0.08
            ? CGVector(dx: steering.dx / length, dy: steering.dy / length)
            : CGVector(dx: facing, dy: 0)
        energy -= Self.boostCost
        boostRemaining = 1.1
        boostCooldown = 4.5
        if energy <= 0 { finish(success: false, reason: .energy) }
        objectWillChange.send()
    }

    func activateSonar() {
        guard canSonar else { return }
        sonarRemaining = 5
        sonarCooldown = 8
        revealNearby(radius: 680)
        announce("Сонар: находки отмечены на карте", duration: 2.5)
        objectWillChange.send()
    }

    func pause() {
        guard state == .playing else { return }
        steering = .zero
        state = .paused
        accumulator = 0
        previousTimestamp = nil
    }

    func togglePause() {
        if state == .paused {
            steering = .zero
            accumulator = 0
            previousTimestamp = nil
            state = .playing
        } else { pause() }
    }

    func startLoop() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: DisplayLinkTarget(engine: self), selector: #selector(DisplayLinkTarget.tick(_:)))
        link.preferredFrameRateRange = CAFrameRateRange(minimum: 30, maximum: 120, preferred: 60)
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    func stopLoop() {
        displayLink?.invalidate()
        displayLink = nil
        previousTimestamp = nil
        pause()
    }

    func step(deltaTime raw: TimeInterval) {
        guard raw.isFinite, raw > 0, state == .playing || state == .ready else { return }
        let dt = min(raw, 0.1)
        if state == .playing {
            accumulator += dt
            while accumulator + 1e-10 >= Self.fixedStep && state == .playing {
                simulate(Self.fixedStep)
                accumulator = max(0, accumulator - Self.fixedStep)
            }
        }
        elapsed += dt
    }

    func current(at point: CGPoint) -> CGVector {
        var result = CGVector.zero
        for zone in level.currents where zone.bounds.contains(point) {
            let edge = min(point.x - zone.bounds.minX, zone.bounds.maxX - point.x,
                           point.y - zone.bounds.minY, zone.bounds.maxY - point.y)
            let strength = min(1, max(0, edge / 38))
            result.dx += zone.velocity.dx * strength
            result.dy += zone.velocity.dy * strength
        }
        return result
    }

    func screenPoint(_ point: CGPoint) -> CGPoint {
        CGPoint(x: point.x - camera.x + viewport.width / 2, y: point.y - camera.y + viewport.height / 2)
    }

    private func simulate(_ delta: TimeInterval) {
        let dt = CGFloat(delta)
        runElapsed += delta
        boostCooldown = max(0, boostCooldown - delta)
        sonarCooldown = max(0, sonarCooldown - delta)
        sonarRemaining = max(0, sonarRemaining - delta)
        invulnerability = max(0, invulnerability - delta)
        noticeRemaining = max(0, noticeRemaining - delta)
        let boosted = boostRemaining > 0
        let flow = current(at: position)
        let drive = boosted ? CGVector(dx: boostDirection.dx * 220, dy: boostDirection.dy * 220)
            : CGVector(dx: steering.dx * Self.cruiseSpeed, dy: steering.dy * Self.cruiseSpeed)
        let targetVelocity = CGVector(dx: drive.dx + flow.dx, dy: drive.dy + flow.dy)
        let response: CGFloat = boosted ? 0.10 : (inputStrength > 0 ? 0.12 : 0.11)
        let decay = exp(-dt / response)
        let previous = position
        position.x += targetVelocity.dx * dt + (velocity.dx - targetVelocity.dx) * response * (1 - decay)
        position.y += targetVelocity.dy * dt + (velocity.dy - targetVelocity.dy) * response * (1 - decay)
        velocity.dx = targetVelocity.dx + (velocity.dx - targetVelocity.dx) * decay
        velocity.dy = targetVelocity.dy + (velocity.dy - targetVelocity.dy) * decay
        boostRemaining = max(0, boostRemaining - delta)
        if abs(drive.dx) > 12 { facing = drive.dx < 0 ? -1 : 1 }
        let thrustCost: CGFloat = boosted ? 1.8 : inputStrength * 1.15
        energy = max(0, energy - thrustCost * dt)

        resolveRocks()
        guard state == .playing else { return }
        constrainToOcean()
        distance += hypot(position.x - previous.x, position.y - previous.y)
        updateMines(delta)
        guard state == .playing else { return }
        collectNearby()
        if energy <= 0 { finish(success: false, reason: .energy); return }
        if hasBlackBox, hypot(position.x - level.base.x, position.y - level.base.y) < 68, speed < 48 {
            finish(success: true)
        }
        if let last = trail.last, hypot(last.x - position.x, last.y - position.y) > 35 {
            trail.append(position)
            if trail.count > 600 { trail.removeFirst() }
        }
        revealNearby(radius: sonarRemaining > 0 ? 680 : 240)
        updateCamera(dt: dt)
    }

    private func resolveRocks() {
        for _ in 0..<3 {
            for rock in level.rocks {
                guard let hit = rock.contact(at: position, radius: Self.hullRadius) else { continue }
                position.x += hit.normal.dx * (hit.penetration + 0.05)
                position.y += hit.normal.dy * (hit.penetration + 0.05)
                let impact = velocity.dx * hit.normal.dx + velocity.dy * hit.normal.dy
                if impact < 0 {
                    velocity.dx -= hit.normal.dx * impact * 1.12
                    velocity.dy -= hit.normal.dy * impact * 1.12
                    if -impact > 78 { takeDamage(); boostRemaining = 0 }
                }
            }
        }
    }

    private func constrainToOcean() {
        let r = Self.hullRadius
        if position.x < r { position.x = r; velocity.dx = max(0, velocity.dx) }
        if position.x > level.size.width - r { position.x = level.size.width - r; velocity.dx = min(0, velocity.dx) }
        if position.y < 110 { position.y = 110; velocity.dy = max(0, velocity.dy) }
        if position.y > level.size.height - 40 { position.y = level.size.height - 40; velocity.dy = min(0, velocity.dy) }
    }

    private func updateMines(_ delta: TimeInterval) {
        for index in mines.indices {
            let distance = hypot(position.x - mines[index].position.x, position.y - mines[index].position.y)
            switch mines[index].phase {
            case .idle:
                if distance < OceanMine.triggerRadius {
                    mines[index].phase = .armed
                    mines[index].timer = OceanMine.fuse
                    announce("Мина активирована — отойди!", duration: 1.5)
                }
            case .armed:
                mines[index].timer -= delta
                if mines[index].timer <= 0 {
                    mines[index].phase = .exploding
                    mines[index].timer = 0.65
                    if distance < OceanMine.blastRadius + Self.hullRadius {
                        takeDamage()
                        let length = max(1, distance)
                        velocity.dx += (position.x - mines[index].position.x) / length * 110
                        velocity.dy += (position.y - mines[index].position.y) / length * 110
                        boostRemaining = 0
                    }
                }
            case .exploding:
                mines[index].timer -= delta
                if mines[index].timer <= 0 { mines[index].phase = .spent }
            case .spent: break
            }
        }
    }

    private func takeDamage() {
        guard invulnerability <= 0, state == .playing else { return }
        invulnerability = 1.4
        damageCount += 1
        if hasShield {
            hasShield = false
            announce("Щит поглотил удар", duration: 2)
        } else {
            hull -= 1
            announce("Корпус повреждён · \(hull)/3", duration: 2)
            if hull <= 0 { finish(success: false, reason: .hull) }
        }
    }

    private func collectNearby() {
        for index in pickups.indices where !pickups[index].collected {
            let pickup = pickups[index]
            guard hypot(pickup.position.x - position.x, pickup.position.y - position.y) < 39 else { continue }
            if pickup.kind == .battery && energy > 97 { continue }
            if pickup.kind == .shield && hasShield { continue }
            pickups[index].collected = true
            pickupCount += 1
            switch pickup.kind {
            case .battery:
                energy = min(100, energy + 30)
                announce("Батарея · +30 энергии")
            case .shield:
                hasShield = true
                announce("Щит · защита от одного удара")
            case .sample:
                samples += 1
                announce("Образец на борту · +75 к добыче")
            case .blackBox:
                hasBlackBox = true
                announce("Чёрный ящик найден. Вернись на базу!", duration: 6)
            }
        }
    }

    private func revealNearby(radius: CGFloat) {
        for pickup in pickups where hypot(position.x - pickup.position.x, position.y - pickup.position.y) < radius {
            revealedPickups.insert(pickup.id)
        }
    }

    private func updateCamera(dt: CGFloat, snap: Bool = false) {
        let look = CGPoint(x: position.x + velocity.dx * 0.65,
                           y: position.y + velocity.dy * 0.45 + 15)
        // Keep the hull in the clear middle of the screen, away from the HUD and stick.
        let marginX = viewport.width / 2, marginY = viewport.height / 2
        let desired = CGPoint(x: min(max(look.x, marginX), max(marginX, level.size.width - marginX)),
                              y: min(max(look.y, marginY), max(marginY, level.size.height - marginY)))
        let amount: CGFloat = snap ? 1 : 1 - exp(-dt * 7)
        camera.x += (desired.x - camera.x) * amount
        camera.y += (desired.y - camera.y) * amount
    }

    private func announce(_ text: String, duration: TimeInterval = 3) {
        notice = text
        noticeRemaining = duration
    }

    private func finish(success: Bool, reason: FailureReason = .hull) {
        steering = .zero
        velocity = .zero
        boostRemaining = 0
        if success {
            score = cargoValue
            if score > bestScore {
                bestScore = score
                defaults.set(score, forKey: Self.bestKey)
            }
            state = .completed
        } else {
            failureReason = reason
            score = 0
            state = .gameOver
        }
    }

    fileprivate func frameDidFire(_ link: CADisplayLink) {
        defer { previousTimestamp = link.timestamp }
        guard let previousTimestamp else { return }
        step(deltaTime: link.timestamp - previousTimestamp)
    }
}

@MainActor
private final class DisplayLinkTarget: NSObject {
    weak var engine: GameEngine?
    init(engine: GameEngine) { self.engine = engine }
    @objc func tick(_ link: CADisplayLink) { engine?.frameDidFire(link) }
}

// MARK: - GameCanvas.swift

enum OceanPalette {
    static let ink = Color(red: 0.025, green: 0.10, blue: 0.15)
    static let teal = Color(red: 0.38, green: 0.89, blue: 0.80)
    static let gold = Color(red: 1, green: 0.77, blue: 0.33)
    static let muted = Color(red: 0.56, green: 0.72, blue: 0.75)
    static let white = Color(red: 0.91, green: 0.96, blue: 0.93)
    static let danger = Color(red: 1, green: 0.43, blue: 0.35)
    static let blue = Color(red: 0.4, green: 0.72, blue: 1)
}

struct GameCanvas: View {
    @ObservedObject var engine: GameEngine
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    private var time: Double { reduceMotion ? 0 : engine.elapsed }

    var body: some View {
        Canvas { context, actualSize in
            let scale = actualSize.width / engine.viewport.width
            context.scaleBy(x: scale, y: scale)
            let size = engine.viewport
            drawWater(in: &context, size: size)
            if engine.state == .ready {
                drawWelcome(in: &context, size: size)
            } else {
                context.drawLayer { world in
                    world.translateBy(x: size.width / 2 - engine.camera.x, y: size.height / 2 - engine.camera.y)
                    drawWorld(in: &world)
                }
            }
            drawSubmarine(in: &context, size: size)
            if engine.sonarRemaining > 0 && engine.state != .ready { drawSonar(in: &context) }
        }
        .background(OceanPalette.ink)
        .accessibilityHidden(true)
    }

    private var visible: CGRect {
        CGRect(x: engine.camera.x - engine.viewport.width / 2 - 120,
               y: engine.camera.y - engine.viewport.height / 2 - 120,
               width: engine.viewport.width + 240, height: engine.viewport.height + 240)
    }

    private func drawWater(in context: inout GraphicsContext, size: CGSize) {
        let depth = engine.state == .ready ? 0.2 : min(1, engine.camera.y / engine.level.size.height)
        context.fill(Path(CGRect(origin: .zero, size: size)), with: .linearGradient(
            Gradient(colors: [Color(red: 0.055 - depth * 0.025, green: 0.27 - depth * 0.12, blue: 0.32 - depth * 0.08),
                              OceanPalette.ink, Color(red: 0.025, green: 0.14, blue: 0.21)]),
            startPoint: .zero, endPoint: CGPoint(x: size.width, y: size.height)))
        for index in 0..<5 {
            let x = CGFloat(index) * 100 - 80 + CGFloat(sin(time * 0.18)) * 12
            var ray = Path()
            ray.move(to: CGPoint(x: x, y: 0))
            ray.addLine(to: CGPoint(x: x + 32, y: 0))
            ray.addLine(to: CGPoint(x: x - 90, y: size.height))
            ray.addLine(to: CGPoint(x: x - 180, y: size.height))
            ray.closeSubpath()
            context.fill(ray, with: .linearGradient(Gradient(colors: [OceanPalette.teal.opacity(0.045 * (1 - depth)), .clear]),
                startPoint: .zero, endPoint: CGPoint(x: 0, y: size.height)))
        }
        for index in 0..<45 {
            let parallax: CGFloat = reduceMotion || engine.state == .ready ? 0 : 0.18
            let rawX = CGFloat((index * 97) % 419) - engine.camera.x * parallax
            let rawY = CGFloat((index * 173) % 937) - engine.camera.y * parallax - CGFloat(time) * 3
            let x = (rawX.truncatingRemainder(dividingBy: size.width) + size.width).truncatingRemainder(dividingBy: size.width)
            let y = (rawY.truncatingRemainder(dividingBy: size.height) + size.height).truncatingRemainder(dividingBy: size.height)
            context.fill(Path(ellipseIn: CGRect(x: x, y: y, width: 2, height: 2)), with: .color(OceanPalette.teal.opacity(0.22)))
        }
        for index in 0..<5 {
            let y = CGFloat(index) * 160 + 160
            var tick = Path()
            tick.move(to: CGPoint(x: 12, y: y))
            tick.addLine(to: CGPoint(x: 21, y: y))
            context.stroke(tick, with: .color(OceanPalette.teal.opacity(0.12)), lineWidth: 1)
        }
    }

    private func drawWelcome(in context: inout GraphicsContext, size: CGSize) {
        let center = CGPoint(x: size.width / 2, y: size.height * 0.43)
        for radius: CGFloat in [76, 108, 140] {
            context.stroke(Path(ellipseIn: CGRect(x: center.x - radius, y: center.y - radius, width: radius * 2, height: radius * 2)),
                           with: .color(OceanPalette.teal.opacity(radius == 76 ? 0.14 : 0.06)),
                           style: StrokeStyle(lineWidth: 0.8, dash: radius == 108 ? [2, 7] : []))
        }
        for layer in 0..<3 {
            var ridge = Path()
            ridge.move(to: CGPoint(x: 0, y: size.height))
            for i in 0...16 {
                let x = CGFloat(i) * size.width / 16
                ridge.addLine(to: CGPoint(x: x, y: size.height - CGFloat(60 + layer * 40) - sin(x * 0.022 + CGFloat(layer)) * 24))
            }
            ridge.addLine(to: CGPoint(x: size.width, y: size.height))
            ridge.closeSubpath()
            context.fill(ridge, with: .color(OceanPalette.teal.opacity(0.025)))
        }
    }

    private func drawWorld(in context: inout GraphicsContext) {
        let size = engine.level.size
        let surface = CGRect(x: 0, y: 0, width: size.width, height: 100)
        context.fill(Path(surface), with: .color(OceanPalette.teal.opacity(0.09)))
        var line = Path()
        line.move(to: CGPoint(x: 0, y: 100))
        line.addLine(to: CGPoint(x: size.width, y: 100))
        context.stroke(line, with: .color(OceanPalette.teal.opacity(0.3)), lineWidth: 2)
        context.fill(Path(CGRect(x: 0, y: size.height - 25, width: size.width, height: 25)), with: .color(OceanPalette.ink))
        for zone in engine.level.currents where visible.intersects(zone.bounds) { drawCurrent(zone, in: &context) }
        for rock in engine.level.rocks where visible.intersects(rock.bounds) { drawRock(rock, in: &context) }
        if visible.insetBy(dx: -80, dy: -80).contains(engine.level.base) { drawBase(in: &context) }
        if visible.insetBy(dx: -120, dy: -120).contains(engine.level.wreck) { drawWreck(in: &context) }
        for pickup in engine.pickups where !pickup.collected && visible.contains(pickup.position) { drawPickup(pickup, in: &context) }
        for mine in engine.mines where visible.contains(mine.position) { drawMine(mine, in: &context) }
        // Small schools belong to the world, making camera movement easy to read.
        for group in 0..<15 {
            let origin = CGPoint(x: CGFloat((group * 347 + 430) % 1450), y: CGFloat(group * 173 + 310))
            guard visible.contains(origin) else { continue }
            for i in 0..<5 {
                let x = origin.x + CGFloat(i * 12) + CGFloat(sin(time * 0.4)) * 14
                let y = origin.y + CGFloat((i * 17) % 29)
                context.fill(Path(ellipseIn: CGRect(x: x, y: y, width: 8, height: 3)), with: .color(OceanPalette.teal.opacity(0.2)))
            }
        }
    }

    private func drawRock(_ rock: OceanRock, in context: inout GraphicsContext) {
        var path = Path()
        path.addLines(rock.vertices)
        path.closeSubpath()
        let bounds = rock.bounds
        context.fill(path, with: .linearGradient(Gradient(colors: [
            Color(red: 0.075, green: 0.28, blue: 0.30), Color(red: 0.055, green: 0.19, blue: 0.23),
            Color(red: 0.025, green: 0.12, blue: 0.18)]),
            startPoint: CGPoint(x: bounds.minX, y: bounds.minY), endPoint: CGPoint(x: bounds.maxX, y: bounds.maxY)))
        context.stroke(path, with: .color(OceanPalette.teal.opacity(0.38)), lineWidth: 1.4)
        context.drawLayer { layer in
            layer.clip(to: path)
            for i in 0..<12 {
                let y = bounds.minY + CGFloat(i) * 52
                var seam = Path()
                seam.move(to: CGPoint(x: bounds.minX - 10, y: y + 40))
                seam.addLine(to: CGPoint(x: bounds.midX - 30, y: y))
                seam.addLine(to: CGPoint(x: bounds.maxX + 10, y: y + 60))
                layer.stroke(seam, with: .color(OceanPalette.ink.opacity(0.35)), lineWidth: 3)
                let x = bounds.minX + CGFloat((i * 37 + rock.id * 43) % max(1, Int(bounds.width)))
                layer.fill(Path(ellipseIn: CGRect(x: x, y: y + 13, width: 4, height: 4)), with: .color(OceanPalette.teal.opacity(0.3)))
            }
        }
        for (index, vertex) in rock.vertices.enumerated() where index.isMultiple(of: 2) {
            let p = CGPoint(x: vertex.x * 0.92 + bounds.midX * 0.08, y: vertex.y * 0.92 + bounds.midY * 0.08)
            drawCoral(at: p, height: 20 + CGFloat(index) * 2, direction: p.y < bounds.midY ? 1 : -1,
                      color: index.isMultiple(of: 4) ? OceanPalette.teal : OceanPalette.danger, in: &context)
        }
    }

    private func drawCurrent(_ zone: OceanCurrent, in context: inout GraphicsContext) {
        let rect = zone.bounds
        context.fill(Path(roundedRect: rect, cornerRadius: 45), with: .color(OceanPalette.blue.opacity(0.045)))
        let vertical = abs(zone.velocity.dy) > abs(zone.velocity.dx)
        let direction: CGFloat = (vertical ? zone.velocity.dy : zone.velocity.dx) > 0 ? 1 : -1
        context.drawLayer { layer in
            layer.clip(to: Path(rect))
            for i in 0..<28 {
                let travel = CGFloat(time) * 25 * direction
                let x = vertical ? rect.minX + CGFloat((i * 41) % max(1, Int(rect.width)))
                    : rect.minX + (CGFloat(i * 43) + travel).truncatingRemainder(dividingBy: rect.width)
                let y = vertical ? rect.minY + (CGFloat(i * 53) + travel).truncatingRemainder(dividingBy: rect.height)
                    : rect.minY + CGFloat((i * 31) % max(1, Int(rect.height)))
                var streak = Path()
                streak.move(to: CGPoint(x: x, y: y))
                streak.addLine(to: CGPoint(x: x + (vertical ? 0 : 18 * direction), y: y + (vertical ? 18 * direction : 0)))
                layer.stroke(streak, with: .color(OceanPalette.blue.opacity(0.2)), style: StrokeStyle(lineWidth: 1, lineCap: .round))
                var arrow = Path()
                if vertical {
                    arrow.move(to: CGPoint(x: x - 3, y: y + 12 * direction))
                    arrow.addLine(to: CGPoint(x: x, y: y + 18 * direction))
                    arrow.addLine(to: CGPoint(x: x + 3, y: y + 12 * direction))
                } else {
                    arrow.move(to: CGPoint(x: x + 12 * direction, y: y - 3))
                    arrow.addLine(to: CGPoint(x: x + 18 * direction, y: y))
                    arrow.addLine(to: CGPoint(x: x + 12 * direction, y: y + 3))
                }
                layer.stroke(arrow, with: .color(OceanPalette.blue.opacity(0.25)), lineWidth: 1)
            }
        }
    }

    private func drawBase(in context: inout GraphicsContext) {
        let p = engine.level.base
        let readyToDock = engine.hasBlackBox
        context.stroke(Path(ellipseIn: CGRect(x: p.x - 68, y: p.y - 68, width: 136, height: 136)),
                       with: .color(OceanPalette.teal.opacity(readyToDock ? 0.7 : 0.22)),
                       style: StrokeStyle(lineWidth: 1.5, dash: [4, 7]))
        var cable = Path()
        cable.move(to: CGPoint(x: p.x, y: 100))
        cable.addLine(to: CGPoint(x: p.x, y: p.y - 55))
        context.stroke(cable, with: .color(OceanPalette.muted.opacity(0.45)), lineWidth: 2)
        let dock = Path(roundedRect: CGRect(x: p.x - 54, y: p.y - 62, width: 108, height: 34), cornerRadius: 9)
        context.fill(dock, with: .color(Color(red: 0.12, green: 0.31, blue: 0.33)))
        context.stroke(dock, with: .color(OceanPalette.teal.opacity(0.6)), lineWidth: 1.2)
        for i in 0..<5 {
            context.fill(Path(roundedRect: CGRect(x: p.x - 41 + CGFloat(i) * 18, y: p.y - 53, width: 10, height: 7), cornerRadius: 2),
                         with: .color(OceanPalette.teal.opacity(0.7)))
        }
        drawText(readyToDock ? "БАЗА · СТЫКОВКА" : "БАЗА · 18", at: CGPoint(x: p.x, y: p.y + 84), color: OceanPalette.teal, in: &context)
        if readyToDock && hypot(engine.position.x - p.x, engine.position.y - p.y) < 100 {
            drawText("Отпусти стик", at: CGPoint(x: p.x, y: p.y + 101), color: OceanPalette.white, in: &context)
        }
    }

    private func drawWreck(in context: inout GraphicsContext) {
        let p = engine.level.wreck
        context.drawLayer { layer in
            layer.translateBy(x: p.x, y: p.y + 49)
            layer.rotate(by: .degrees(-9))
            var hull = Path()
            hull.move(to: CGPoint(x: -95, y: -20))
            hull.addLine(to: CGPoint(x: -75, y: 25))
            hull.addLine(to: CGPoint(x: 54, y: 30))
            hull.addLine(to: CGPoint(x: 91, y: -13))
            hull.addLine(to: CGPoint(x: 22, y: -9))
            hull.addLine(to: CGPoint(x: 11, y: 9))
            hull.addLine(to: CGPoint(x: -8, y: -16))
            hull.closeSubpath()
            layer.fill(hull, with: .color(Color(red: 0.24, green: 0.28, blue: 0.27)))
            layer.stroke(hull, with: .color(OceanPalette.gold.opacity(0.25)), lineWidth: 1.5)
            layer.fill(Path(roundedRect: CGRect(x: -60, y: -46, width: 45, height: 30), cornerRadius: 4),
                       with: .color(Color(red: 0.15, green: 0.25, blue: 0.27)))
            for i in 0..<3 {
                layer.fill(Path(ellipseIn: CGRect(x: -52 + CGFloat(i) * 14, y: -36, width: 7, height: 7)), with: .color(OceanPalette.ink))
            }
            drawCoral(at: CGPoint(x: 45, y: 10), height: 38, direction: -1, color: OceanPalette.teal, in: &layer)
        }
        drawText("ASTER · ЗАТОНУВШИЙ КОРАБЛЬ", at: CGPoint(x: p.x - 8, y: p.y + 109), color: OceanPalette.muted, in: &context)
    }

    private func drawPickup(_ pickup: OceanPickup, in context: inout GraphicsContext) {
        let p = CGPoint(x: pickup.position.x, y: pickup.position.y + CGFloat(sin(time * 1.8 + Double(pickup.id))) * 3)
        let color: Color = pickup.kind == .shield ? OceanPalette.blue : (pickup.kind == .battery ? OceanPalette.teal : OceanPalette.gold)
        context.fill(Path(ellipseIn: CGRect(x: p.x - 32, y: p.y - 32, width: 64, height: 64)),
                     with: .radialGradient(Gradient(colors: [color.opacity(0.17), .clear]), center: p, startRadius: 2, endRadius: 32))
        switch pickup.kind {
        case .battery:
            let body = Path(roundedRect: CGRect(x: p.x - 8, y: p.y - 12, width: 16, height: 24), cornerRadius: 4)
            context.fill(body, with: .color(OceanPalette.ink))
            context.stroke(body, with: .color(color), lineWidth: 1.5)
            context.fill(Path(CGRect(x: p.x - 3, y: p.y - 16, width: 6, height: 4)), with: .color(color))
            for i in 0..<3 { context.fill(Path(CGRect(x: p.x - 4, y: p.y - 7 + CGFloat(i) * 6, width: 8, height: 3)), with: .color(color)) }
        case .shield:
            var shield = Path()
            shield.move(to: CGPoint(x: p.x, y: p.y - 15))
            shield.addLine(to: CGPoint(x: p.x + 12, y: p.y - 9))
            shield.addQuadCurve(to: CGPoint(x: p.x, y: p.y + 15), control: CGPoint(x: p.x + 13, y: p.y + 6))
            shield.addQuadCurve(to: CGPoint(x: p.x - 12, y: p.y - 9), control: CGPoint(x: p.x - 13, y: p.y + 6))
            shield.closeSubpath()
            context.fill(shield, with: .color(color.opacity(0.15)))
            context.stroke(shield, with: .color(color), lineWidth: 1.5)
        case .sample:
            var crystal = Path()
            crystal.addLines([CGPoint(x: p.x, y: p.y - 12), CGPoint(x: p.x + 9, y: p.y), CGPoint(x: p.x, y: p.y + 12), CGPoint(x: p.x - 9, y: p.y)])
            crystal.closeSubpath()
            context.fill(crystal, with: .linearGradient(Gradient(colors: [OceanPalette.white, color]),
                startPoint: CGPoint(x: p.x - 8, y: p.y - 12), endPoint: CGPoint(x: p.x + 8, y: p.y + 12)))
        case .blackBox:
            let box = Path(roundedRect: CGRect(x: p.x - 18, y: p.y - 12, width: 36, height: 24), cornerRadius: 5)
            context.fill(box, with: .color(OceanPalette.ink))
            context.stroke(box, with: .color(color), lineWidth: 2)
            context.fill(Path(CGRect(x: p.x - 13, y: p.y - 10, width: 4, height: 20)), with: .color(color))
            context.fill(Path(CGRect(x: p.x + 9, y: p.y - 10, width: 4, height: 20)), with: .color(color))
            context.fill(Path(ellipseIn: CGRect(x: p.x - 2, y: p.y - 2, width: 4, height: 4)), with: .color(OceanPalette.teal))
        }
        let labels: [PickupKind: String] = [.battery: "+30 ЭНЕРГИИ", .shield: "ЩИТ", .sample: "ОБРАЗЕЦ · 75", .blackBox: "ЧЁРНЫЙ ЯЩИК"]
        if hypot(engine.position.x - p.x, engine.position.y - p.y) < 200 || pickup.kind == .blackBox {
            drawText(labels[pickup.kind] ?? "", at: CGPoint(x: p.x, y: p.y + 31), color: color, in: &context)
        }
    }

    private func drawMine(_ mine: OceanMine, in context: inout GraphicsContext) {
        let p = mine.position
        if mine.phase == .spent { return }
        if mine.phase == .exploding {
            let progress = 1 - mine.timer / 0.65
            let radius = OceanMine.blastRadius * CGFloat(0.3 + progress * 0.7)
            let blast = Path(ellipseIn: CGRect(x: p.x - radius, y: p.y - radius, width: radius * 2, height: radius * 2))
            context.fill(blast, with: .color(OceanPalette.danger.opacity((1 - progress) * 0.2)))
            context.stroke(blast, with: .color(OceanPalette.gold.opacity(1 - progress)), lineWidth: 3)
            return
        }
        let armed = mine.phase == .armed
        let color = armed ? OceanPalette.danger : OceanPalette.muted
        if armed || engine.sonarRemaining > 0 {
            let radius = OceanMine.blastRadius
            let danger = Path(ellipseIn: CGRect(x: p.x - radius, y: p.y - radius, width: radius * 2, height: radius * 2))
            context.fill(danger, with: .color(OceanPalette.danger.opacity(armed ? 0.055 : 0.025)))
            context.stroke(danger, with: .color(OceanPalette.danger.opacity(armed ? 0.6 : 0.25)),
                           style: StrokeStyle(lineWidth: 1, dash: [4, 5]))
        }
        for i in 0..<8 {
            let a = CGFloat(i) * .pi / 4
            var spike = Path()
            spike.move(to: CGPoint(x: p.x + cos(a) * 12, y: p.y + sin(a) * 12))
            spike.addLine(to: CGPoint(x: p.x + cos(a) * 21, y: p.y + sin(a) * 21))
            context.stroke(spike, with: .color(color), style: StrokeStyle(lineWidth: 3, lineCap: .round))
        }
        let body = Path(ellipseIn: CGRect(x: p.x - 14, y: p.y - 14, width: 28, height: 28))
        context.fill(body, with: .color(OceanPalette.ink))
        context.stroke(body, with: .color(color), lineWidth: 2)
        context.fill(Path(ellipseIn: CGRect(x: p.x - 4, y: p.y - 4, width: 8, height: 8)),
                     with: .color(OceanPalette.danger.opacity(armed ? 1 : 0.65)))
        if armed {
            var fuse = Path()
            fuse.addArc(center: p, radius: 29, startAngle: .degrees(-90),
                        endAngle: .degrees(-90 + 360 * mine.timer / OceanMine.fuse), clockwise: false)
            context.stroke(fuse, with: .color(OceanPalette.danger), style: StrokeStyle(lineWidth: 3, lineCap: .round))
        }
    }

    private func drawSonar(in context: inout GraphicsContext) {
        guard !reduceMotion else { return }
        let p = engine.screenPoint(engine.position)
        let progress = 1 - engine.sonarRemaining / 5
        let radius = CGFloat(progress) * 760
        context.stroke(Path(ellipseIn: CGRect(x: p.x - radius, y: p.y - radius, width: radius * 2, height: radius * 2)),
                       with: .color(OceanPalette.teal.opacity((1 - progress) * 0.5)), lineWidth: 1.5)
    }

    private func drawText(_ text: String, at point: CGPoint, color: Color, in context: inout GraphicsContext) {
        context.draw(Text(text).font(.system(size: 9, weight: .semibold, design: .monospaced)).foregroundStyle(color), at: point)
    }

    private func drawCoral(at p: CGPoint, height: CGFloat, direction: CGFloat, color: Color, in context: inout GraphicsContext) {
        var path = Path()
        path.move(to: p)
        path.addQuadCurve(to: CGPoint(x: p.x + 3, y: p.y + height * direction), control: CGPoint(x: p.x - 4, y: p.y + height * direction * 0.6))
        path.move(to: CGPoint(x: p.x, y: p.y + height * direction * 0.4))
        path.addLine(to: CGPoint(x: p.x - 9, y: p.y + height * direction * 0.73))
        path.addLine(to: CGPoint(x: p.x - 10, y: p.y + height * direction))
        path.move(to: CGPoint(x: p.x + 1, y: p.y + height * direction * 0.65))
        path.addLine(to: CGPoint(x: p.x + 10, y: p.y + height * direction * 0.88))
        context.stroke(path, with: .color(color.opacity(0.8)), style: StrokeStyle(lineWidth: 2.5, lineCap: .round, lineJoin: .round))
    }

    private func drawSubmarine(in context: inout GraphicsContext, size: CGSize) {
        let ready = engine.state == .ready
        let center = ready ? CGPoint(x: size.width / 2, y: size.height * 0.43 + CGFloat(sin(time * 1.7)) * 5) : engine.screenPoint(engine.position)
        let boatScale: CGFloat = ready ? 1.6 : 0.86
        let facing: CGFloat = ready ? 1 : engine.facing
        for index in 0..<7 {
            let phase = (CGFloat(time) * (engine.isThrustActive ? 65 : 34) + CGFloat(index) * 14)
                .truncatingRemainder(dividingBy: 100)
            let radius = (1 + phase / 55) * boatScale
            let x = center.x - (48 + phase * 0.65) * boatScale * facing
            let y = center.y + CGFloat(sin(Double(phase) * 0.06 + Double(index))) * 8 - phase * 0.09
            context.stroke(Path(ellipseIn: CGRect(x: x, y: y, width: radius * 2, height: radius * 2)),
                           with: .color(OceanPalette.teal.opacity(Double(1 - phase / 100) * 0.4)), lineWidth: 0.8)
        }
        if !ready && engine.hasShield {
            context.stroke(Path(ellipseIn: CGRect(x: center.x - 38, y: center.y - 36, width: 76, height: 72)),
                           with: .color(OceanPalette.blue.opacity(0.65)), lineWidth: 1.5)
        }
        context.drawLayer { layer in
            layer.translateBy(x: center.x, y: center.y)
            layer.rotate(by: .radians(ready ? -0.055 : engine.submarineRotationRadians * Double(facing)))
            layer.scaleBy(x: boatScale * facing, y: boatScale)
            if !ready && engine.invulnerability > 0 { layer.opacity = reduceMotion ? 0.65 : 0.45 + abs(sin(time * 18)) * 0.55 }
            var beam = Path()
            beam.move(to: CGPoint(x: 32, y: -3))
            beam.addLine(to: CGPoint(x: 186, y: -59))
            beam.addQuadCurve(to: CGPoint(x: 186, y: 59), control: CGPoint(x: 207, y: 0))
            beam.addLine(to: CGPoint(x: 32, y: 6))
            beam.closeSubpath()
            layer.fill(beam, with: .linearGradient(Gradient(colors: [OceanPalette.gold.opacity(0.12), .clear]),
                startPoint: CGPoint(x: 32, y: 0), endPoint: CGPoint(x: 180, y: 0)))

            let darkGold = Color(red: 0.63, green: 0.34, blue: 0.12)
            var fin = Path()
            fin.move(to: CGPoint(x: -23, y: -8))
            fin.addLine(to: CGPoint(x: -42, y: -23))
            fin.addLine(to: CGPoint(x: -39, y: 20))
            fin.addLine(to: CGPoint(x: -22, y: 10))
            fin.closeSubpath()
            layer.fill(fin, with: .color(darkGold))
            layer.fill(Path(roundedRect: CGRect(x: -46, y: -3, width: 15, height: 6), cornerRadius: 3), with: .color(OceanPalette.muted))
            let propellerHeight = CGFloat(7 + abs(sin(time * (engine.isThrustActive ? 35 : 19))) * 20)
            layer.fill(Path(roundedRect: CGRect(x: -47, y: -propellerHeight / 2, width: 4, height: propellerHeight), cornerRadius: 2),
                       with: .color(OceanPalette.white.opacity(0.9)))
            let cabin = Path(roundedRect: CGRect(x: -14, y: -27, width: 28, height: 19), cornerRadius: 7)
            layer.fill(cabin, with: .linearGradient(Gradient(colors: [OceanPalette.gold, darkGold]),
                startPoint: CGPoint(x: 0, y: -27), endPoint: CGPoint(x: 0, y: -9)))
            var scope = Path()
            scope.move(to: CGPoint(x: -2, y: -26))
            scope.addLine(to: CGPoint(x: -2, y: -36))
            scope.addQuadCurve(to: CGPoint(x: 2, y: -40), control: CGPoint(x: -2, y: -40))
            scope.addLine(to: CGPoint(x: 9, y: -40))
            layer.stroke(scope, with: .color(OceanPalette.gold), style: StrokeStyle(lineWidth: 4, lineCap: .round))
            layer.fill(Path(roundedRect: CGRect(x: 7, y: -43, width: 5, height: 6), cornerRadius: 1.5), with: .color(OceanPalette.ink))
            let hull = Path(roundedRect: CGRect(x: -34, y: -18, width: 72, height: 37), cornerRadius: 18.5)
            layer.fill(hull, with: .linearGradient(Gradient(colors: [Color(red: 1, green: 0.88, blue: 0.53), OceanPalette.gold, Color(red: 0.87, green: 0.49, blue: 0.16)]),
                startPoint: CGPoint(x: 0, y: -18), endPoint: CGPoint(x: 0, y: 21)))
            layer.stroke(hull, with: .color(Color(red: 1, green: 0.88, blue: 0.59).opacity(0.65)), lineWidth: 0.8)
            let shine = Path(roundedRect: CGRect(x: -23, y: -14, width: 39, height: 3), cornerRadius: 1.5)
            layer.fill(shine, with: .color(.white.opacity(0.38)))
            for x: CGFloat in [-13, 11] {
                layer.fill(Path(ellipseIn: CGRect(x: x - 9, y: -9, width: 18, height: 18)), with: .color(darkGold))
                layer.fill(Path(ellipseIn: CGRect(x: x - 7.5, y: -7.5, width: 15, height: 15)), with: .color(Color(red: 0.98, green: 0.88, blue: 0.61)))
                let glass = Path(ellipseIn: CGRect(x: x - 5.8, y: -5.8, width: 11.6, height: 11.6))
                layer.fill(glass, with: .linearGradient(Gradient(colors: [Color(red: 0.10, green: 0.32, blue: 0.39), OceanPalette.teal]),
                    startPoint: CGPoint(x: x, y: -6), endPoint: CGPoint(x: x, y: 6)))
                layer.fill(Path(ellipseIn: CGRect(x: x - 3.7, y: -3.7, width: 3.5, height: 2.5)), with: .color(.white.opacity(0.7)))
            }
            for x: CGFloat in [-24, -2, 24] {
                layer.fill(Path(ellipseIn: CGRect(x: x, y: 12, width: 1.5, height: 1.5)), with: .color(darkGold.opacity(0.8)))
            }
            layer.fill(Path(roundedRect: CGRect(x: -9, y: 16, width: 26, height: 5), cornerRadius: 2), with: .color(darkGold))
            layer.fill(Path(roundedRect: CGRect(x: 33, y: -5, width: 6, height: 10), cornerRadius: 3), with: .color(Color(red: 1, green: 0.94, blue: 0.73)))
        }
    }

}

// MARK: - GameView.swift

struct ContentView: View {
    @StateObject private var engine: GameEngine
    @Environment(\.scenePhase) private var scenePhase
    @State private var showingMap = false

    init(engine: GameEngine = GameEngine()) {
        _engine = StateObject(wrappedValue: engine)
    }

    var body: some View {
        GeometryReader { proxy in
            ZStack {
                GameCanvas(engine: engine)
                if engine.state == .ready {
                    welcome(size: proxy.size, insets: proxy.safeAreaInsets)
                } else {
                    instruments(insets: proxy.safeAreaInsets)
                        .allowsHitTesting(engine.state == .playing)
                        .accessibilityHidden(engine.state != .playing)
                    if engine.state == .playing {
                        objectivePointer(size: proxy.size)
                        controls(insets: proxy.safeAreaInsets)
                    }
                    if engine.state != .playing {
                        OceanPalette.ink.opacity(0.78).ignoresSafeArea()
                        if showingMap {
                            mapPanel(height: proxy.size.height)
                        } else {
                            resultPanel
                        }
                    }
                }
            }
            .onAppear { engine.resize(to: proxy.size); engine.startLoop() }
            .onDisappear { engine.stopLoop() }
            .onChange(of: proxy.size) { _, size in engine.resize(to: size) }
        }
        .ignoresSafeArea()
        .statusBarHidden()
        .persistentSystemOverlays(.hidden)
        .onChange(of: scenePhase) { _, phase in if phase != .active { engine.pause() } }
        .sensoryFeedback(.selection, trigger: engine.pickupCount)
        .sensoryFeedback(.error, trigger: engine.damageCount)
        .sensoryFeedback(.success, trigger: engine.state == .completed)
        .preferredColorScheme(.dark)
    }

    private func welcome(size: CGSize, insets: EdgeInsets) -> some View {
        VStack(spacing: 0) {
            HStack {
                brand
                Spacer()
                Label("\(engine.bestScore)", systemImage: "trophy")
                    .font(.system(size: 13, weight: .semibold, design: .monospaced))
                    .foregroundStyle(OceanPalette.gold)
                    .padding(.horizontal, 13).padding(.vertical, 10)
                    .background(OceanPalette.gold.opacity(0.08), in: Capsule())
                    .overlay(Capsule().stroke(OceanPalette.gold.opacity(0.15), lineWidth: 1))
                    .accessibilityLabel("Лучшая доставленная добыча: \(engine.bestScore)")
            }
            .padding(.top, max(insets.top, 48) + 12)
            VStack(spacing: 12) {
                Text("СВОБОДНЫЙ ОКЕАН")
                    .font(.system(size: 10, weight: .semibold, design: .monospaced))
                    .tracking(3).foregroundStyle(OceanPalette.teal)
                Text("Курс на глубину.")
                    .font(.system(size: size.height < 720 ? 35 : 41, weight: .bold, design: .rounded))
                    .tracking(-1.5).foregroundStyle(OceanPalette.white)
                    .minimumScaleFactor(0.7).lineLimit(1)
                Text("Найди чёрный ящик. Вернись с добычей.")
                    .font(.system(size: 12, weight: .medium)).foregroundStyle(OceanPalette.muted)
                    .multilineTextAlignment(.center)
            }
            .padding(.top, size.height * 0.045)
            Spacer(minLength: 0)
            VStack(spacing: size.height < 720 ? 16 : 22) {
                HStack(spacing: 7) {
                    Circle().fill(OceanPalette.teal).frame(width: 4, height: 4)
                    Text("ЭКСПЕДИЦИЯ 01 / ЗАТОНУВШИЙ ASTER")
                        .font(.system(size: 9, weight: .medium, design: .monospaced)).tracking(1)
                }.foregroundStyle(OceanPalette.teal.opacity(0.85))
                HStack(spacing: 0) {
                    instruction(icon: "arrow.up.and.down.and.arrow.left.and.right", title: "Свободный курс", detail: "Тяни стик в любую сторону")
                    Rectangle().fill(OceanPalette.teal.opacity(0.15)).frame(width: 1, height: 48)
                    instruction(icon: "dot.radiowaves.left.and.right", title: "Сонар и форсаж", detail: "Ищи. Маневрируй. Исследуй.")
                }
                .padding(.vertical, 17)
                .background(OceanPalette.ink.opacity(0.45), in: RoundedRectangle(cornerRadius: 22))
                .overlay(RoundedRectangle(cornerRadius: 22).stroke(OceanPalette.teal.opacity(0.12), lineWidth: 1))
                Button {
                    showingMap = false
                    engine.startGame()
                } label: {
                    HStack { Spacer(); Text("Начать экспедицию"); Spacer(); Image(systemName: "arrow.right") }
                }
                .buttonStyle(DiveButtonStyle()).accessibilityIdentifier("startDive")
                Text("Береги корпус и заряд на обратный путь")
                    .font(.system(size: 11, weight: .medium)).foregroundStyle(OceanPalette.muted)
            }
            .padding(.bottom, max(insets.bottom, 24) + 16)
        }
        .padding(.horizontal, 26)
    }

    private var brand: some View {
        HStack(spacing: 9) {
            Text("18").font(.system(size: 15, weight: .bold, design: .monospaced))
                .foregroundStyle(OceanPalette.teal).frame(width: 35, height: 35)
                .overlay(RoundedRectangle(cornerRadius: 10).stroke(OceanPalette.teal.opacity(0.3), lineWidth: 1))
            VStack(alignment: .leading, spacing: 3) {
                Text("PODLODKA").font(.system(size: 11, weight: .bold)).tracking(2).foregroundStyle(OceanPalette.white)
                Text("D I V E  /  iOS CREW").font(.system(size: 8, weight: .medium, design: .monospaced)).foregroundStyle(OceanPalette.muted)
            }
        }
    }

    private func instruction(icon: String, title: String, detail: String) -> some View {
        VStack(spacing: 7) {
            Image(systemName: icon).font(.system(size: 19, weight: .medium)).foregroundStyle(OceanPalette.gold)
            Text(title).font(.system(size: 12, weight: .semibold)).foregroundStyle(OceanPalette.white)
            Text(detail).font(.system(size: 9)).foregroundStyle(OceanPalette.muted)
                .lineLimit(1).minimumScaleFactor(0.8)
        }.frame(maxWidth: .infinity)
    }

    private func instruments(insets: EdgeInsets) -> some View {
        VStack(spacing: 12) {
            HStack(spacing: 8) {
                VStack(alignment: .leading, spacing: 5) {
                    Text("ЭКСПЕДИЦИЯ 01 · \(engine.depth) М")
                        .font(.system(size: 9, weight: .medium, design: .monospaced))
                        .tracking(1.2).foregroundStyle(OceanPalette.muted)
                    Text(engine.hasBlackBox ? "Вернись на базу" : "Найди чёрный ящик")
                        .font(.system(size: 17, weight: .semibold, design: .rounded))
                        .foregroundStyle(engine.hasBlackBox ? OceanPalette.teal : OceanPalette.white)
                        .lineLimit(1).minimumScaleFactor(0.8)
                }
                .allowsHitTesting(false)
                Spacer(minLength: 0)
                hudButton("map", label: "Карта экспедиции", id: "openMap") { engine.pause(); showingMap = true }
                hudButton("pause.fill", label: "Пауза", id: "pauseDive", action: engine.pause)
            }
            HStack(spacing: 13) {
                HStack(spacing: 6) {
                    Image(systemName: "bolt.fill").font(.system(size: 11))
                    Text("\(Int(ceil(engine.energy)))%")
                        .font(.system(size: 13, weight: .semibold, design: .monospaced)).frame(minWidth: 35, alignment: .leading)
                    Capsule().fill(OceanPalette.teal.opacity(0.14)).frame(width: 40, height: 4)
                        .overlay(alignment: .leading) {
                            Capsule().fill(engine.energy < 25 ? OceanPalette.danger : OceanPalette.teal)
                                .frame(width: 40 * engine.energy / 100, height: 4)
                        }
                }
                .foregroundStyle(engine.energy < 25 ? OceanPalette.danger : OceanPalette.teal)
                .accessibilityElement(children: .ignore).accessibilityLabel("Энергия: \(Int(engine.energy)) процентов")
                HStack(spacing: 4) {
                    ForEach(0..<3) { index in
                        Image(systemName: index < engine.hull ? "heart.fill" : "heart")
                            .font(.system(size: 11)).foregroundStyle(index < engine.hull ? OceanPalette.danger : OceanPalette.muted.opacity(0.4))
                    }
                    if engine.hasShield { Image(systemName: "shield.fill").font(.system(size: 11)).foregroundStyle(OceanPalette.blue) }
                }
                .accessibilityElement(children: .ignore).accessibilityLabel("Корпус: \(engine.hull) из 3. \(engine.hasShield ? "Щит активен" : "")")
                Spacer(minLength: 0)
                Label("\(engine.cargoValue)", systemImage: "shippingbox")
                    .font(.system(size: 12, weight: .medium, design: .monospaced)).foregroundStyle(OceanPalette.gold)
                    .accessibilityLabel("Груз на борту: \(engine.cargoValue)")
            }
            .allowsHitTesting(false)
            HStack(spacing: 6) {
                Image(systemName: "location.north.fill")
                    .rotationEffect(.radians(atan2(engine.target.y - engine.position.y, engine.target.x - engine.position.x) + .pi / 2))
                Text("\(engine.hasBlackBox ? "БАЗА" : "СИГНАЛ") · \(engine.targetDistance) М")
                    .tracking(1)
                Spacer()
                if engine.hasBlackBox { Label("ЯЩИК НА БОРТУ", systemImage: "checkmark").foregroundStyle(OceanPalette.teal) }
            }
            .font(.system(size: 9, weight: .semibold, design: .monospaced))
            .foregroundStyle(OceanPalette.gold.opacity(0.85)).allowsHitTesting(false)
            Spacer()
        }
        .padding(.horizontal, 22).padding(.top, max(insets.top, 48) + 9)
        .background(alignment: .top) {
            LinearGradient(colors: [OceanPalette.ink.opacity(0.92), OceanPalette.ink.opacity(0.7), .clear], startPoint: .top, endPoint: .bottom)
                .frame(height: 190).allowsHitTesting(false)
        }
    }

    private func hudButton(_ icon: String, label: String, id: String, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Image(systemName: icon).font(.system(size: 14, weight: .semibold))
                .foregroundStyle(OceanPalette.white).frame(width: 42, height: 42)
                .background(OceanPalette.ink.opacity(0.6), in: Circle())
                .overlay(Circle().stroke(OceanPalette.teal.opacity(0.22), lineWidth: 1))
        }.buttonStyle(.plain).accessibilityLabel(label).accessibilityIdentifier(id)
    }

    private func controls(insets: EdgeInsets) -> some View {
        VStack(spacing: 4) {
            Spacer()
            if engine.energy < 25 {
                Label("Мало энергии — ищи батарею или возвращайся", systemImage: "bolt.trianglebadge.exclamationmark")
                    .font(.system(size: 10, weight: .semibold)).foregroundStyle(OceanPalette.danger)
                    .padding(.horizontal, 12).padding(.vertical, 8)
                    .background(OceanPalette.ink.opacity(0.85), in: Capsule()).allowsHitTesting(false)
            }
            if engine.noticeRemaining > 0 {
                Text(engine.notice).font(.system(size: 11, weight: .medium))
                    .foregroundStyle(OceanPalette.white).multilineTextAlignment(.center)
                    .padding(.horizontal, 15).padding(.vertical, 9)
                    .background(OceanPalette.ink.opacity(0.85), in: Capsule())
                    .padding(.horizontal, 16).allowsHitTesting(false)
            }
            HStack(alignment: .center, spacing: 0) {
                SteeringPad(onInput: engine.setSteering)
                    .frame(width: 174, height: 158)
                Spacer(minLength: 0)
                VStack(spacing: 12) {
                    HStack(spacing: 12) {
                        AbilityButton(icon: "dot.radiowaves.left.and.right", title: "СОНАР",
                                      detail: engine.sonarCooldown > 0 ? "\(Int(ceil(engine.sonarCooldown))) с" : "Поиск",
                                      progress: 1 - engine.sonarCooldown / 8, enabled: engine.canSonar,
                                      color: OceanPalette.teal, action: engine.activateSonar)
                            .accessibilityIdentifier("sonar")
                        AbilityButton(icon: "bolt.fill", title: "ФОРСАЖ",
                                      detail: engine.boostCooldown > 0 ? "\(Int(ceil(engine.boostCooldown))) с" : "−7 энергии",
                                      progress: 1 - engine.boostCooldown / 4.5, enabled: engine.canBoost,
                                      color: OceanPalette.gold, action: engine.activateBoost)
                            .accessibilityIdentifier("boost")
                    }
                    if engine.runElapsed < 12 {
                        Text("Отпусти стик, чтобы зависнуть")
                            .font(.system(size: 8)).foregroundStyle(OceanPalette.muted)
                            .allowsHitTesting(false)
                    }
                }
                .padding(.trailing, 18)
            }
            .padding(.bottom, max(insets.bottom, 20))
            .background(LinearGradient(colors: [.clear, OceanPalette.ink.opacity(0.82)], startPoint: .top, endPoint: .bottom).allowsHitTesting(false))
        }
    }

    private func objectivePointer(size: CGSize) -> some View {
        let point = engine.screenPoint(engine.target)
        let scale = size.width / engine.viewport.width
        let bounds = CGRect(x: 29, y: 192, width: engine.viewport.width - 58, height: max(80, engine.viewport.height - 415))
        let x = min(max(point.x, bounds.minX), bounds.maxX)
        let y = min(max(point.y, bounds.minY), bounds.maxY)
        return Group {
            if !bounds.contains(point) {
                Image(systemName: "location.north.fill")
                    .font(.system(size: 16, weight: .medium))
                    .rotationEffect(.radians(atan2(engine.target.y - engine.position.y, engine.target.x - engine.position.x) + .pi / 2))
                    .foregroundStyle(engine.hasBlackBox ? OceanPalette.teal : OceanPalette.gold)
                    .frame(width: 33, height: 33)
                    .background(OceanPalette.ink.opacity(0.7), in: Circle())
                    .overlay(Circle().stroke(OceanPalette.gold.opacity(0.25), lineWidth: 1))
                    .position(x: x * scale, y: y * scale)
            }
        }.allowsHitTesting(false).accessibilityHidden(true)
    }

    private func mapPanel(height: CGFloat) -> some View {
        VStack(spacing: 18) {
            HStack {
                VStack(alignment: .leading, spacing: 5) {
                    Text("КАРТА ЭКСПЕДИЦИИ").font(.system(size: 9, weight: .medium, design: .monospaced)).tracking(1.5).foregroundStyle(OceanPalette.teal)
                    Text("Сектор «Aster»").font(.system(size: 24, weight: .semibold, design: .rounded)).foregroundStyle(OceanPalette.white)
                }
                Spacer()
                Text("ПАУЗА").font(.system(size: 9, weight: .medium, design: .monospaced)).foregroundStyle(OceanPalette.muted)
            }
            ExpeditionMap(engine: engine).frame(height: min(395, height * 0.49))
                .background(OceanPalette.ink.opacity(0.8), in: RoundedRectangle(cornerRadius: 16))
            VStack(spacing: 9) {
                HStack(spacing: 13) {
                    mapKey("circle.fill", "Ты", .white)
                    mapKey("house.fill", "База", OceanPalette.teal)
                    mapKey("shippingbox.fill", "Цель", OceanPalette.gold)
                    mapKey("xmark", "Мины", OceanPalette.danger)
                }
                HStack(spacing: 15) {
                    mapKey("battery.100percent", "Батарея", OceanPalette.teal)
                    mapKey("shield", "Щит", OceanPalette.blue)
                    mapKey("diamond", "Образец", OceanPalette.gold)
                }
            }
            Text("Сонар отмечает находки. Линия — пройденный путь.")
                .font(.system(size: 10)).foregroundStyle(OceanPalette.muted).multilineTextAlignment(.center)
            Button {
                showingMap = false
                engine.togglePause()
            } label: {
                HStack { Spacer(); Text("Вернуться в океан"); Spacer(); Image(systemName: "arrow.right") }
            }.buttonStyle(DiveButtonStyle()).accessibilityIdentifier("closeMap")
        }
        .padding(22).frame(maxWidth: 380)
        .background(Color(red: 0.035, green: 0.15, blue: 0.20), in: RoundedRectangle(cornerRadius: 27))
        .overlay(RoundedRectangle(cornerRadius: 27).stroke(OceanPalette.teal.opacity(0.18), lineWidth: 1))
        .padding(.horizontal, 20)
    }

    private func mapKey(_ icon: String, _ text: String, _ color: Color) -> some View {
        Label(text, systemImage: icon).font(.system(size: 10)).foregroundStyle(color)
    }

    private var resultPanel: some View {
        let paused = engine.state == .paused
        let success = engine.state == .completed
        let title = paused ? "Можно выдохнуть." : (success ? "Груз доставлен." : "Океан сильнее.")
        let detail = paused ? "Экспедиция на паузе. Заряд сохраняется." : (success ? "Чёрный ящик на базе. Хорошая работа, капитан." : (engine.failureReason == .energy ? "Заряд закончился. Груз остался на глубине." : "Корпус не выдержал. Груз остался на глубине."))
        return VStack(spacing: 22) {
            Image(systemName: paused ? "pause.fill" : (success ? "shippingbox.fill" : "water.waves"))
                .font(.system(size: 28, weight: .medium)).foregroundStyle(success ? OceanPalette.gold : OceanPalette.teal)
                .frame(width: 72, height: 72)
                .background(OceanPalette.teal.opacity(0.07), in: Circle())
                .overlay(Circle().stroke(OceanPalette.teal.opacity(0.15), lineWidth: 1))
            VStack(spacing: 10) {
                Text(paused ? "ТИХАЯ ВОДА" : (engine.isNewRecord ? "НОВЫЙ РЕКОРД ЭКСПЕДИЦИИ" : "ЭКСПЕДИЦИЯ ЗАВЕРШЕНА"))
                    .font(.system(size: 8, weight: .medium, design: .monospaced)).tracking(1.5).foregroundStyle(OceanPalette.teal)
                Text(title).font(.system(size: 30, weight: .bold, design: .rounded)).tracking(-0.8)
                    .foregroundStyle(OceanPalette.white).lineLimit(1).minimumScaleFactor(0.75)
                Text(detail).font(.system(size: 13)).foregroundStyle(OceanPalette.muted).multilineTextAlignment(.center).lineSpacing(3)
            }
            HStack(spacing: 0) {
                resultStat(paused ? engine.cargoValue : engine.score, title: paused ? "ГРУЗ НА БОРТУ" : "ДОСТАВЛЕНО", highlighted: true)
                Rectangle().fill(OceanPalette.teal.opacity(0.15)).frame(width: 1, height: 44)
                resultStat(engine.bestScore, title: "ЛУЧШАЯ ДОБЫЧА", highlighted: false)
            }
            .padding(.vertical, 16).background(OceanPalette.teal.opacity(0.045), in: RoundedRectangle(cornerRadius: 18))
            VStack(spacing: 12) {
                Button {
                    if paused { engine.togglePause() } else { engine.startGame() }
                } label: {
                    HStack { Spacer(); Text(paused ? "Продолжить" : "Новая экспедиция"); Spacer(); Image(systemName: paused ? "play.fill" : "arrow.clockwise") }
                }.buttonStyle(DiveButtonStyle()).accessibilityIdentifier(paused ? "resumeDive" : "retryDive")
                if paused {
                    Button("Открыть карту") { showingMap = true }
                        .font(.system(size: 13, weight: .medium)).foregroundStyle(OceanPalette.teal).frame(minHeight: 35)
                }
                Button("На поверхность") { showingMap = false; engine.returnToMenu() }
                    .font(.system(size: 13, weight: .medium)).foregroundStyle(OceanPalette.muted).frame(minHeight: 35)
                    .accessibilityIdentifier("returnToMenu")
            }
        }
        .padding(25).frame(maxWidth: 360)
        .background(Color(red: 0.035, green: 0.15, blue: 0.20), in: RoundedRectangle(cornerRadius: 30))
        .overlay(RoundedRectangle(cornerRadius: 30).stroke(OceanPalette.teal.opacity(0.18), lineWidth: 1))
        .padding(.horizontal, 25)
    }

    private func resultStat(_ value: Int, title: String, highlighted: Bool) -> some View {
        VStack(spacing: 6) {
            Text("\(value)").font(.system(size: 33, weight: .semibold, design: .rounded)).monospacedDigit()
                .foregroundStyle(highlighted ? OceanPalette.white : OceanPalette.gold)
            Text(title).font(.system(size: 8, weight: .medium, design: .monospaced)).tracking(0.6).foregroundStyle(OceanPalette.muted)
        }.frame(maxWidth: .infinity)
    }
}

/// A native touch surface keeps ownership of the steering finger while the
/// other thumb presses an ability, and handles cancellation explicitly.
private struct SteeringPad: UIViewRepresentable {
    let onInput: (CGVector) -> Void

    func makeUIView(context: Context) -> SteeringSurface {
        let view = SteeringSurface()
        view.onInput = onInput
        return view
    }

    func updateUIView(_ view: SteeringSurface, context: Context) { view.onInput = onInput }
    static func dismantleUIView(_ view: SteeringSurface, coordinator: ()) { view.releaseInput() }
}

private final class SteeringSurface: UIView {
    var onInput: ((CGVector) -> Void)?
    private var finger: UITouch?
    private var origin: CGPoint?
    private var knob = CGVector.zero

    override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = .clear
        isMultipleTouchEnabled = true
        isAccessibilityElement = true
        accessibilityLabel = "Руль подлодки. Тяни в нужном направлении. Отпусти, чтобы остановиться."
        accessibilityIdentifier = "steeringPad"
    }

    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard finger == nil, let touch = touches.first else { return }
        finger = touch
        let point = touch.location(in: self)
        origin = CGPoint(x: min(max(point.x, 53), bounds.width - 53), y: min(max(point.y, 53), bounds.height - 53))
        updateInput(touch.location(in: self))
    }

    override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard let finger, touches.contains(finger) else { return }
        updateInput(finger.location(in: self))
    }

    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard let finger, touches.contains(finger) else { return }
        releaseInput()
    }

    override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) { releaseInput() }

    func releaseInput() {
        finger = nil
        origin = nil
        knob = .zero
        onInput?(.zero)
        setNeedsDisplay()
    }

    private func updateInput(_ point: CGPoint) {
        guard let origin else { return }
        let dx = point.x - origin.x, dy = point.y - origin.y
        let length = hypot(dx, dy)
        let scale = length > 44 ? 44 / length : 1
        knob = CGVector(dx: dx * scale, dy: dy * scale)
        onInput?(CGVector(dx: knob.dx / 44, dy: knob.dy / 44))
        setNeedsDisplay()
    }

    override func draw(_ rect: CGRect) {
        guard let context = UIGraphicsGetCurrentContext() else { return }
        let center = origin ?? CGPoint(x: bounds.midX, y: bounds.midY)
        let teal = UIColor(OceanPalette.teal)
        func circle(_ center: CGPoint, radius: CGFloat, fill: UIColor?, stroke: UIColor?) {
            let rect = CGRect(x: center.x - radius, y: center.y - radius, width: radius * 2, height: radius * 2)
            if let fill { context.setFillColor(fill.cgColor); context.fillEllipse(in: rect) }
            if let stroke { context.setStrokeColor(stroke.cgColor); context.setLineWidth(1); context.strokeEllipse(in: rect) }
        }
        circle(center, radius: 53, fill: UIColor(OceanPalette.ink).withAlphaComponent(0.3), stroke: teal.withAlphaComponent(finger == nil ? 0.18 : 0.45))
        circle(center, radius: 38, fill: nil, stroke: teal.withAlphaComponent(0.08))
        context.setStrokeColor(teal.withAlphaComponent(0.23).cgColor)
        context.move(to: CGPoint(x: center.x - 5, y: center.y)); context.addLine(to: CGPoint(x: center.x + 5, y: center.y))
        context.move(to: CGPoint(x: center.x, y: center.y - 5)); context.addLine(to: CGPoint(x: center.x, y: center.y + 5))
        context.strokePath()
        circle(CGPoint(x: center.x + knob.dx, y: center.y + knob.dy), radius: 21.5,
               fill: teal.withAlphaComponent(finger == nil ? 0.09 : 0.28), stroke: teal.withAlphaComponent(0.55))
    }
}

private struct AbilityButton: View {
    let icon: String
    let title: String
    let detail: String
    let progress: Double
    let enabled: Bool
    let color: Color
    let action: () -> Void
    var body: some View {
        Button(action: action) {
            VStack(spacing: 7) {
                ZStack {
                    Circle().fill(OceanPalette.ink.opacity(0.85))
                    Circle().stroke(color.opacity(0.15), lineWidth: 2)
                    Circle().trim(from: 0, to: min(1, max(0, progress)))
                        .stroke(color.opacity(enabled ? 0.7 : 0.3), style: StrokeStyle(lineWidth: 2, lineCap: .round))
                        .rotationEffect(.degrees(-90))
                    Image(systemName: icon).font(.system(size: 20, weight: .medium)).foregroundStyle(color.opacity(enabled ? 1 : 0.4))
                }.frame(width: 55, height: 55)
                Text(title).font(.system(size: 8, weight: .semibold, design: .monospaced)).tracking(0.6).foregroundStyle(color)
                Text(detail).font(.system(size: 9)).foregroundStyle(OceanPalette.muted)
            }.frame(width: 64)
        }.buttonStyle(.plain).disabled(!enabled).accessibilityLabel("\(title), \(detail)")
    }
}

private struct ExpeditionMap: View {
    @ObservedObject var engine: GameEngine
    var body: some View {
        Canvas { context, size in
            let scale = min((size.width - 28) / engine.level.size.width, (size.height - 32) / engine.level.size.height)
            let offset = CGPoint(x: (size.width - engine.level.size.width * scale) / 2, y: 16)
            func point(_ p: CGPoint) -> CGPoint { CGPoint(x: p.x * scale + offset.x, y: p.y * scale + offset.y) }
            for zone in engine.level.currents {
                let rect = CGRect(x: zone.bounds.minX * scale + offset.x, y: zone.bounds.minY * scale + offset.y,
                                  width: zone.bounds.width * scale, height: zone.bounds.height * scale)
                context.fill(Path(roundedRect: rect, cornerRadius: 5), with: .color(OceanPalette.blue.opacity(0.10)))
            }
            for rock in engine.level.rocks {
                var path = Path(); path.addLines(rock.vertices.map(point)); path.closeSubpath()
                context.fill(path, with: .color(OceanPalette.teal.opacity(0.13)))
                context.stroke(path, with: .color(OceanPalette.teal.opacity(0.28)), lineWidth: 0.7)
            }
            var trail = Path(); trail.addLines(engine.trail.map(point))
            context.stroke(trail, with: .color(OceanPalette.white.opacity(0.22)), style: StrokeStyle(lineWidth: 1, dash: [2, 3]))
            for mine in engine.mines where mine.phase != .spent {
                let p = point(mine.position)
                var cross = Path()
                cross.move(to: CGPoint(x: p.x - 3, y: p.y - 3)); cross.addLine(to: CGPoint(x: p.x + 3, y: p.y + 3))
                cross.move(to: CGPoint(x: p.x + 3, y: p.y - 3)); cross.addLine(to: CGPoint(x: p.x - 3, y: p.y + 3))
                context.stroke(cross, with: .color(OceanPalette.danger.opacity(0.8)), lineWidth: 1.5)
            }
            for pickup in engine.pickups where !pickup.collected && pickup.kind != .blackBox && engine.revealedPickups.contains(pickup.id) {
                let p = point(pickup.position)
                let color = pickup.kind == .battery ? OceanPalette.teal : (pickup.kind == .shield ? OceanPalette.blue : OceanPalette.gold)
                let rect = CGRect(x: p.x - 3, y: p.y - 3, width: 6, height: 6)
                context.fill(Path(roundedRect: rect, cornerRadius: pickup.kind == .battery ? 1 : 3), with: .color(color))
            }
            let base = point(engine.level.base), wreck = point(engine.level.wreck), boat = point(engine.position)
            context.stroke(Path(ellipseIn: CGRect(x: base.x - 6, y: base.y - 6, width: 12, height: 12)), with: .color(OceanPalette.teal), lineWidth: 1.4)
            context.draw(Text("БАЗА").font(.system(size: 9, weight: .medium)).foregroundStyle(OceanPalette.teal), at: CGPoint(x: base.x, y: base.y - 16))
            context.fill(Path(roundedRect: CGRect(x: wreck.x - 5, y: wreck.y - 4, width: 10, height: 8), cornerRadius: 2), with: .color(engine.hasBlackBox ? OceanPalette.muted : OceanPalette.gold))
            context.draw(Text(engine.hasBlackBox ? "ASTER" : "ЯЩИК").font(.system(size: 9, weight: .medium)).foregroundStyle(OceanPalette.gold), at: CGPoint(x: wreck.x, y: wreck.y + 15))
            context.fill(Path(ellipseIn: CGRect(x: boat.x - 4, y: boat.y - 4, width: 8, height: 8)), with: .color(.white))
            context.stroke(Path(ellipseIn: CGRect(x: boat.x - 8, y: boat.y - 8, width: 16, height: 16)), with: .color(.white.opacity(0.4)), lineWidth: 1)
        }
        .accessibilityLabel("Карта сектора: база на северо-западе, корабль на юго-востоке. Между рифами есть западный обход и центральный путь через мины.")
    }
}

private struct DiveButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label.font(.system(size: 15, weight: .bold)).foregroundStyle(OceanPalette.ink)
            .padding(.horizontal, 20).frame(height: 56)
            .background(LinearGradient(colors: [Color(red: 1, green: 0.83, blue: 0.46), OceanPalette.gold], startPoint: .top, endPoint: .bottom), in: RoundedRectangle(cornerRadius: 18))
            .overlay(RoundedRectangle(cornerRadius: 18).stroke(.white.opacity(0.15), lineWidth: 1))
            .shadow(color: OceanPalette.gold.opacity(0.1), radius: 16, y: 4)
            .scaleEffect(configuration.isPressed ? 0.97 : 1)
            .animation(.easeOut(duration: 0.15), value: configuration.isPressed)
    }
}
