#!/usr/bin/env python3
"""Rebuild the standalone Dactyl source from the actual iOS game."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
sources = [root / "PodlodkaDive" / name for name in ("GameEngine.swift", "GameCanvas.swift", "GameView.swift")]
imports = set()
sections = []
for source in sources:
    lines = source.read_text().splitlines()
    imports.update(line for line in lines if line.startswith("import "))
    body = "\n".join(line for line in lines if not line.startswith("import ")).strip()
    if source.name == "GameView.swift":
        body = body.replace("struct GameView: View", "struct ContentView: View", 1)
    sections.append(f"// MARK: - {source.name}\n\n{body}")
header = "// Generated by scripts/sync-dactyl.py. Edit PodlodkaDive/ sources, then regenerate.\n"
output = header + "\n".join(sorted(imports)) + "\n\n" + "\n\n".join(sections) + "\n"
(root / "PodlodkaDive-Dactyl.swift").write_text(output)
print("Updated PodlodkaDive-Dactyl.swift")
